#version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    #veri silinmesini engellemek için
    #volumes:
     # - redis-data:/data
    #command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

  backend:
    build:
      context: ./backend
    container_name: leaderboard-api
    ports:
      - "5259:80"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  frontend:
    build:
      context: ./frontend
    container_name: leaderboard-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:80   #http://localhost:5259

volumes:
  redis-data:
